const $=id=>document.getElementById(id);let recognition=null,listening=false;
function log(m){const d=document.createElement("div");d.textContent=`${new Date().toLocaleTimeString()}  ${m}`;$("log").prepend(d)}
function setState(d){$("blueLed").className="led "+(d.blue?"blue-on":"blue-off");$("greenLed").className="led "+(d.green?"green-on":"green-off");$("blueText").textContent=d.blue?"ON":"OFF";$("greenText").textContent=d.green?"ON":"OFF";if(d.recognition!==undefined&&d.recognition)$("recognition").textContent=d.recognition;if(d.message)$("message").textContent=d.message;$("portText").textContent=`Port：${d.port||"未設定"}`;const b=$("connectionBadge");b.textContent=d.connected?"● 已連線":"● 未連線";b.className="badge "+(d.connected?"online":"offline")}
async function getStatus(){try{setState(await(await fetch("/api/status")).json())}catch(e){log("⚠️ 無法取得伺服器狀態")}}
async function connectBoard(){const d=await(await fetch("/api/connect",{method:"POST"})).json();setState(d);log(d.message)}
async function disconnectBoard(){const d=await(await fetch("/api/disconnect",{method:"POST"})).json();setState(d);log(d.message)}
async function sendText(text){text=text.trim();if(!text)return;$("recognition").textContent=text;try{const d=await(await fetch("/api/recognition",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})})).json();setState(d);log(d.accepted?`指令：${d.command} → ${d.message}`:`非控制指令：${text} → LED 狀態保持不變`);if(d.ok&&d.accepted)speak(d.message)}catch(e){$("message").textContent="❌ 伺服器通訊失敗";log("❌ 無法連線 Flask 後端")}}
function speak(text){if(!("speechSynthesis"in window))return;const u=new SpeechSynthesisUtterance(text.replace(/^✓\s*/,""));u.lang="zh-TW";speechSynthesis.cancel();speechSynthesis.speak(u)}
function initSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$("speechSupport").textContent="⚠️ 此瀏覽器不支援語音辨識，建議最新版 Chrome/Edge。文字測試仍可用。";$("voiceBtn").disabled=true;return}recognition=new SR();recognition.lang="zh-TW";recognition.continuous=false;recognition.interimResults=false;recognition.onstart=()=>{listening=true;$("voiceBtn").textContent="⏹️ 正在聆聽…";$("voiceBtn").classList.add("listening");log("🎙️ 開始語音辨識")};recognition.onresult=e=>{const t=e.results[0][0].transcript.trim();log(`🎙️ 辨識結果：${t}`);sendText(t)};recognition.onerror=e=>{$("message").textContent=`⚠️ 語音辨識失敗：${e.error}`;log(`⚠️ 語音辨識失敗：${e.error}；LED 狀態保持不變`)};recognition.onend=()=>{listening=false;$("voiceBtn").textContent="🎙️ 開始語音辨識";$("voiceBtn").classList.remove("listening")}}
$("connectBtn").onclick=connectBoard;$("disconnectBtn").onclick=disconnectBoard;$("executeBtn").onclick=()=>sendText($("commandInput").value);$("commandInput").addEventListener("keydown",e=>{if(e.key==="Enter")sendText($("commandInput").value)});document.querySelectorAll("[data-command]").forEach(b=>b.onclick=()=>{$("commandInput").value=b.dataset.command;sendText(b.dataset.command)});$("voiceBtn").onclick=()=>{if(!recognition)return;if(listening)recognition.stop();else recognition.start()};initSpeech();getStatus();setInterval(getStatus,1000);
